# Generated by Django 5.2.6 on 2025-09-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chainage_km', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=200)),
                ('inspection_date', models.DateField()),
                ('structure_type', models.CharField(max_length=100)),
                ('structure_no', models.CharField(max_length=50)),
                ('rating', models.CharField(choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('good', 'Good')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('cleaning', 'Cleaning Required')], max_length=10)),
                ('side', models.CharField(choices=[('lhs', 'LHS'), ('rhs', 'RHS'), ('both', 'Both')], max_length=10)),
                ('map_coordinates', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.bridge')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='observation_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_before', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspection.observation')),
            ],
        ),
        migrations.AddField(
            model_name='bridge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.project'),
        ),
        migrations.CreateModel(
            name='SummaryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_total', models.IntegerField(default=0)),
                ('critical_lhs', models.IntegerField(default=0)),
                ('critical_rhs', models.IntegerField(default=0)),
                ('moderate_total', models.IntegerField(default=0)),
                ('moderate_lhs', models.IntegerField(default=0)),
                ('moderate_rhs', models.IntegerField(default=0)),
                ('cleaning_total', models.IntegerField(default=0)),
                ('cleaning_lhs', models.IntegerField(default=0)),
                ('cleaning_rhs', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspection.bridge')),
            ],
        ),
    ]
