# Generated by Django 5.2.6 on 2025-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationimage',
            name='is_before',
        ),
        migrations.RemoveField(
            model_name='observationimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='observationimage',
            name='image_type',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10),
        ),
    ]
