# Generated by Django 5.2.6 on 2025-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_remove_observationimage_is_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observationimage',
            name='image',
            field=models.ImageField(upload_to='observations/'),
        ),
    ]
