# Generated by Django 5.2.6 on 2025-09-21 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_alter_observationimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationimage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='observationimage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='observationimage',
            name='side',
            field=models.CharField(choices=[('lhs', 'LHS'), ('rhs', 'RHS'), ('both', 'Both')], default='lhs', max_length=10),
        ),
        migrations.AddField(
            model_name='observationimage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
