# Generated by Django 5.2.6 on 2025-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_observationimage_latitude_observationimage_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
    ]
