# Generated by Django 5.2.7 on 2025-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_observation_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bridge',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='map_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='map_images/'),
        ),
    ]
