# Generated by Django 5.2.7 on 2025-10-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_bridge_latitude_bridge_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='map_coordinates',
        ),
    ]
