# Generated by Django 5.2.7 on 2025-10-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_remove_observation_map_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='map_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
