# Generated by Django 5.2.7 on 2025-10-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_observation_map_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='chainage_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bridge',
            name='chainage_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bridge',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bridge',
            name='structure_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
