# Generated by Django 5.2.7 on 2025-10-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_bridge_chainage_from_bridge_chainage_to_bridge_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='chainage_from',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='chainage_to',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='level',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='structure_id',
        ),
    ]
