# Generated by Django 5.2.7 on 2025-10-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_bridge_chainage_from_bridge_chainage_to_bridge_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationimage',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
